name: 'IDC test matrix generator'
description: 'Generates a matrix of test suites'
author: 'emetsger@jhu.edu'
inputs:
  testdir:
    required: false
    description: 'Directory (relative to the CWD) containing test controllers (e.g. the directory containing 01-end-to-end.sh)'
    default: 'tests/'
  glob:
    required: false
    description: 'File glob matching tests to include in the matrix'
    default: '*.sh'
runs:
  using: 'node12'
  main: 'dist/index.js'
